INSERT INTO BOOKS (ID,AUTHOR,ISBN,PUBLISH_DATE,TITLE) VALUES(1,'TEST BERKAY','TESTISBN','2001-01-01','TEST KITAP');
INSERT INTO BOOKS (ID,AUTHOR,ISBN,PUBLISH_DATE,TITLE) VALUES(2,'TEST BERKAY2','TESTISIN','2001-01-01','TEST KITAP');
INSERT INTO BOOKS (ID,AUTHOR,ISBN,PUBLISH_DATE,TITLE) VALUES(3,'TEST BERKAY3','TISBWFN','2001-01-01','TEST KITAP');
INSERT INTO BOOKS (ID,AUTHOR,ISBN,PUBLISH_DATE,TITLE) VALUES(4,'TEST BERKAY4','SDGSIBN','2001-01-01','TEST KITAP');